'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import StoreProvider from './StoreProvider'
import { createClient } from '@/utils/supabase/client'
import { useDispatch } from 'react-redux'
import { updateStockList, clearStock, clearStockList } from '@/lib/store'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Ekios',
//   // description: 'Generated by create next app',
// }

export default function RootLayout({children}) {
  const supabase = createClient()
  const dispatch = useDispatch()

  const { data } = supabase.auth.onAuthStateChange((event, session) => {
    console.log(event, session)
    if (event === 'SIGNED_IN') {
      dispatch(updateStockList())
    } else if (event === 'SIGNED_OUT') {
      dispatch(clearStock())
      dispatch(clearStockList())
    }
  })
  
  // call unsubscribe to remove the callback
  data.subscription.unsubscribe()

  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <div>hi</div>
          {children}
        </body>
      </html>
    </StoreProvider>
  )
}
